### ISSUE TITLE
Feature request: a way to actually make $VERSION a trial version

### ISSUE THREAD

**Issue by cxw42** [Grinnz/App-RewriteVersion#1]
Thank you for this tool - I have recently started using perl-bump-version in my development (e.g., [blatant plug](https://github.com/cxw42/Test-OnlySome) :) ).  I tripped over the `-t` option to perl-bump-version just now because it doesn't actually affect the version.  The synopsis for [perl-bump-version](https://metacpan.org/pod/distribution/App-RewriteVersion/script/perl-bump-version#SYNOPSIS) says that `-t` will "mark version as a trial version".  I thought that meant it would add an underscore or `-TRIAL` marker.  However, as the docs for [App::RewriteVersion](https://metacpan.org/pod/App::RewriteVersion#rewrite_version) point out, that's not what `is_trial` does.

Would you be willing to add a new option that will, in addition to adding `# TRIAL` to the source code, also add `-TRIAL` (or bump to `-TRIAL1` &c.) to the contents of `$VERSION`?  E.g.:

- `0.001001` -> `0.001001-TRIAL` when run with the new option
- `0.001001` -> `0.001002` as usual when run without the new option
- `0.001001-TRIAL` -> `0.001001-TRIAL1` -> `0.001001-TRIAL2` ... when run with the new option
- `0.001001-TRIAL` (or `-TRIALn` for any `n =~ /\d+/`) -> `0.001002` when run without the new option

Thank you for considering this request!

**Comment by Grinnz** [comment]
-TRIAL is not allowed in version numbers. This must be set in the name of the distribution archive you upload, which is unfortunately out of the scope of this tool.

**Comment by cxw42** [comment]
@Grinnz thanks for pointing that out - it's a subtlety I had missed.  I see that EUMM doesn't pick up `-TRIAL` ([example](https://metacpan.org/source/ANDK/CPAN-2.16-TRIAL2/META.json#L83)).  Would you be willing instead to add an option to insert an underscore?  E.g., `0.001000`->`0.001_001`?  EUMM does pick up on that, and it's what DAGOLDEN recommends in his article.

(For future readers, or myself later: [article](https://xdg.me/blog/version-numbers-should-be-boring/); [CPAN trial-release documentation](https://www.cpan.org/modules/04pause.html#developerreleases); [notes about CPAN trial-release handling](https://books.google.com/books?id=qhV2XYSgTaMC&pg=PA410&lpg=PA410&dq=%22cpan%22+%22version%22+%22trial%22&source=bl&ots=j0LfDHgTal&sig=Aft9G5z077wnBM-rvApGH0BUZEs&hl=en&sa=X&ved=2ahUKEwig_eOPrZ3fAhUPJTQIHYCYAKYQ6AEwCXoECAQQAQ#v=onepage&q=%22cpan%22%20%22version%22%20%22trial%22&f=false); [recommendation not to use `-TRIAL`](http://blogs.perl.org/users/oliver_gorwits/2011/10/releasing-trialdevbeta-versions-with-distzilla.html); [Dist::Zilla trial releases](http://dzil.org/tutorial/release.html))

**Comment by Grinnz** [comment]
He recommended it back then, but not recently, see the documentation for [the RewriteVersion plugin](https://metacpan.org/pod/Dist::Zilla::Plugin::BumpVersionAfterRelease#Using-underscore-in-decimal-$VERSION) which this tool is based on. If you want to modify a version in a way other than a simple bump you should do that yourself in the main module. Unfortunately using raw EUMM does not afford you convenient options for this like using dzil does.

**Comment by Grinnz** [comment]
I am considering making allow_decimal_underscores default though, since outside of dzil it is still the most convenient option.

**Comment by Grinnz** [comment]
For your additional persusal, here is the [PAUSE operating model](https://github.com/andk/pause/blob/master/doc/operating-model.md#35-factors-considering-in-the-indexing-phase) which describes how PAUSE determines whether to index a release. (It doesn't mention release_status but it also respects this setting.)

**Comment by cxw42** [comment]
OK - thanks!
